import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  introSidebar: [{type: 'autogenerated', dirName: 'overview'}],
  devSidebar: [{type: 'autogenerated', dirName: 'devel'}],
  docsSidebar: [
    'user/index',
    {
      type: 'category',
      label: 'Configuration profiles',
      link: {
        type: 'doc', id: 'user/profile'
      },
      items: [{type: 'autogenerated', dirName: 'user/profile'}]
    },
    {
      type: 'category',
      label: 'Guides & HowTos',
      link: {
        type: 'generated-index',
        description:
          "This section contains a collection of specific documents explaining how to achieve " +
          "some concrete tasks using Agama. For a more general overview, refer to the " +
          "'Get started' and 'Documentation' sections."
      },
      items: [{type: 'autogenerated', dirName: 'user/guides'}]
    },
    {
      type: 'category',
      label: 'Reference',
      link: {
        type: 'generated-index',
        description:
          'This section contains detailed reference documentation for several aspects of Agama, ' +
          'like the exact format of each section of the profile or all the possible commands ' +
          'and arguments for the command-line interface.'
      },
      items: [{type: 'autogenerated', dirName: 'user/reference'}]
    },
  ]
};

export default sidebars;
