name: Test deployment

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Use a surge.sh URL
        run: .github/workflows/test-deploy-patch-url.rb

      - name: Test build website
        run: yarn build

      - name: Install surge
        run: yarn add surge

      - name: Deploy to surge.sh
        run: .github/workflows/test-deploy-upload.rb
        env:
          GH_TOKEN: ${{ github.token }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
          STATUS_SHA: ${{ github.event.after }}
